[package]
name = "rustcord"
version = "0.1.0"
authors = ["iraizo <groebner.loron@gmail.com>", "Ashley <admin@trapacid.icu"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.9.1"
iced = "0.1"